version: "3"


tasks:
  default:
    silent: true
    cmds:
      - task --list

  generate:
    desc: Generate the GraphQL client and schema
    deps:
      - fetch-schema
    cmds:
      - task generate:client

  generate:client:
    sources:
      - query/**/*.graphql
    generates:
      - go-client/models.go
      - go-client/graphqlclient.go
      - go-client/models.go
    method: checksum
    cmds:
      - go generate generate/generate.go

  fetch-schema:
    cmds:
      - rover graph fetch Openlane-0dedz@current > schema/schema.graphql
