model:
  package: graphclient
  filename: ../graphclient/models.go
client:
  package: graphclient
  filename: ../graphclient/graphclient.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.String
  JSON:
    model:
      - github.com/theopenlane/entx.RawMessage
  Address:
    model:
      - github.com/theopenlane/core/common/models.Address
  Price:
    model:
      - github.com/theopenlane/core/common/models.Price
  AssessmentObjective:
    model:
      - github.com/theopenlane/core/common/models.AssessmentObjective
  AssessmentMethod:
    model:
      - github.com/theopenlane/core/common/models.AssessmentMethod
  Reference:
    model:
      - github.com/theopenlane/core/common/models.Reference
  ImplementationGuidance:
    model:
      - github.com/theopenlane/core/common/models.ImplementationGuidance
  ExampleEvidence:
    model:
      - github.com/theopenlane/core/common/models.ExampleEvidence
  TestingProcedures:
    model:
      - github.com/theopenlane/core/common/models.TestingProcedures
  EvidenceRequests:
    model:
      - github.com/theopenlane/core/common/models.EvidenceRequests
  VersionBump:
    model:
      - github.com/theopenlane/core/common/models.VersionBump
  DateTime:
    model: github.com/theopenlane/core/common/models.DateTime
  AAGUID:
    model: github.com/theopenlane/core/common/models.AAGUID
  JobConfiguration:
    model: github.com/theopenlane/core/common/models.JobConfiguration
  JobCadence:
    model: github.com/theopenlane/core/common/models.JobCadence
  Change:
    model: github.com/theopenlane/core/common/models.Change
  AuditLogOrderField:
    model: github.com/theopenlane/core/common/models.AuditLogOrderField
  CredentialSet:
    model:
      - github.com/theopenlane/core/common/models.CredentialSet
  SearchContext:
    model:
      - github.com/theopenlane/core/common/models.SearchContext
  SearchSnippet:
    model:
      - github.com/theopenlane/core/common/models.SearchSnippet
  WorkflowDefinitionDocument:
    model:
      - github.com/theopenlane/core/common/models.WorkflowDefinitionDocument
  WorkflowDefinitionSchema:
    model:
      - github.com/theopenlane/core/common/models.WorkflowDefinitionSchema
  WorkflowInstanceContext:
    model:
      - github.com/theopenlane/core/common/models.WorkflowInstanceContext
  WorkflowEventPayload:
    model:
      - github.com/theopenlane/core/common/models.WorkflowEventPayload
  WorkflowAssignmentApproval:
    model:
      - github.com/theopenlane/core/common/models.WorkflowAssignmentApproval
  WorkflowAssignmentInvalidation:
    model:
      - github.com/theopenlane/core/common/models.WorkflowAssignmentInvalidation
  WorkflowAssignmentRejection:
    model:
      - github.com/theopenlane/core/common/models.WorkflowAssignmentRejection
schema: ["../schema/schema.graphql"]
query: ["../query/*.graphql"]
generate:
  clientV2: true
  clientInterfaceName: "GraphClient"
  query: false
  mutation: false
